version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
shallow_clone: true
dotnet_csproj:
  patch: true
  file: '**\Plugin.SecureStorage.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps:
    mkdir .\Plugin.SecureStorage\bin\Debug
    nuget restore
build:
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: 6VQDOrtL+wrE0ND8y2XOYEk2c8c7AjJQFKRELQ3iRqV5Mk6Mcg3A1icl7fDuE9Lh
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master