version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
shallow_clone: true
dotnet_csproj:
  patch: true
  file: '**\Plugin.SecureStorage.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps:
    nuget restore Plugin.SecureStorage_CI.sln
build:
  project: Plugin.SecureStorage_CI.sln
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: rTPwMJQ8zMZT/AAfDBnPDvBOBKbcqwmgpBix5lldiXBfKvzK/ElIpzuRUsEZNvS6
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master